import type { Category } from "./categories";

// ~19 well-known DECEASED figures across categories so the game is playable
// immediately. Coordinates are approximate (good enough for a world-map pin).
// Portrait URLs use Wikimedia Commons Special:FilePath (redirects to the file);
// if one fails to load the UI falls back to initials.
//
// Add more later: append entries here and re-run `npx convex run seed:run`
// (insertion is idempotent on `slug`).

export type SeedFigure = {
  slug: string;
  firstName: string;
  lastName: string;
  fullName: string;
  aliases: string[];
  primaryCategory: Category;
  categories: Category[];
  difficulty: "easy" | "medium" | "hard";
  notability: number;
  birth: Place;
  death: Place;
  wikipediaUrl: string;
  imageUrl: string;
  funFact: string;
  tags?: string[];
};

type Place = {
  placeLabel: string;
  modernCountry: string;
  city: string;
  lat: number;
  lng: number;
  year: number;
  month?: number;
  day?: number;
  circa?: boolean;
};

const img = (file: string) =>
  `https://commons.wikimedia.org/wiki/Special:FilePath/${file}?width=320`;

export const SEED_FIGURES: SeedFigure[] = [
  {
    slug: "albert-einstein",
    firstName: "Albert",
    lastName: "Einstein",
    fullName: "Albert Einstein",
    aliases: ["Einstein"],
    primaryCategory: "science",
    categories: ["science"],
    difficulty: "easy",
    notability: 99,
    birth: { placeLabel: "Ulm, German Empire", modernCountry: "Germany", city: "Ulm", lat: 48.4011, lng: 9.9876, year: 1879, month: 3, day: 14 },
    death: { placeLabel: "Princeton, New Jersey, USA", modernCountry: "United States", city: "Princeton", lat: 40.3573, lng: -74.6672, year: 1955, month: 4, day: 18 },
    wikipediaUrl: "https://en.wikipedia.org/wiki/Albert_Einstein",
    imageUrl: img("Albert_Einstein_Head.jpg"),
    funFact: "He turned down an offer to become the second president of Israel.",
  },
  {
    slug: "isaac-newton",
    firstName: "Isaac",
    lastName: "Newton",
    fullName: "Isaac Newton",
    aliases: ["Newton", "Sir Isaac Newton"],
    primaryCategory: "science",
    categories: ["science"],
    difficulty: "medium",
    notability: 96,
    birth: { placeLabel: "Woolsthorpe, England", modernCountry: "United Kingdom", city: "Woolsthorpe-by-Colsterworth", lat: 52.8092, lng: -0.6306, year: 1643, month: 1, day: 4 },
    death: { placeLabel: "Kensington, London, England", modernCountry: "United Kingdom", city: "London", lat: 51.5018, lng: -0.1925, year: 1727, month: 3, day: 31 },
    wikipediaUrl: "https://en.wikipedia.org/wiki/Isaac_Newton",
    imageUrl: img("GodfreyKneller-IsaacNewton-1689.jpg"),
    funFact: "He served as Warden of the Royal Mint and pursued counterfeiters.",
  },
  {
    slug: "marie-curie",
    firstName: "Marie",
    lastName: "Curie",
    fullName: "Marie Curie",
    aliases: ["Marie Sklodowska Curie", "Madame Curie", "Maria Sklodowska"],
    primaryCategory: "science",
    categories: ["science"],
    difficulty: "medium",
    notability: 95,
    birth: { placeLabel: "Warsaw, Russian Empire", modernCountry: "Poland", city: "Warsaw", lat: 52.2297, lng: 21.0122, year: 1867, month: 11, day: 7 },
    death: { placeLabel: "Passy, Haute-Savoie, France", modernCountry: "France", city: "Passy", lat: 45.9237, lng: 6.7106, year: 1934, month: 7, day: 4 },
    wikipediaUrl: "https://en.wikipedia.org/wiki/Marie_Curie",
    imageUrl: img("Marie_Curie_c1920.jpg"),
    funFact: "She is the only person to win Nobel Prizes in two different sciences.",
  },
  {
    slug: "charles-darwin",
    firstName: "Charles",
    lastName: "Darwin",
    fullName: "Charles Darwin",
    aliases: ["Darwin"],
    primaryCategory: "science",
    categories: ["science"],
    difficulty: "medium",
    notability: 93,
    birth: { placeLabel: "Shrewsbury, England", modernCountry: "United Kingdom", city: "Shrewsbury", lat: 52.7069, lng: -2.7553, year: 1809, month: 2, day: 12 },
    death: { placeLabel: "Downe, Kent, England", modernCountry: "United Kingdom", city: "Downe", lat: 51.3316, lng: 0.0539, year: 1882, month: 4, day: 19 },
    wikipediaUrl: "https://en.wikipedia.org/wiki/Charles_Darwin",
    imageUrl: img("Charles_Darwin_seated_crop.jpg"),
    funFact: "He ate specimens of many animals he studied, from iguanas to owls.",
  },
  {
    slug: "vincent-van-gogh",
    firstName: "Vincent",
    lastName: "van Gogh",
    fullName: "Vincent van Gogh",
    aliases: ["Van Gogh"],
    primaryCategory: "art",
    categories: ["art"],
    difficulty: "easy",
    notability: 94,
    birth: { placeLabel: "Zundert, Netherlands", modernCountry: "Netherlands", city: "Zundert", lat: 51.4697, lng: 4.6553, year: 1853, month: 3, day: 30 },
    death: { placeLabel: "Auvers-sur-Oise, France", modernCountry: "France", city: "Auvers-sur-Oise", lat: 49.0708, lng: 2.1703, year: 1890, month: 7, day: 29 },
    wikipediaUrl: "https://en.wikipedia.org/wiki/Vincent_van_Gogh",
    imageUrl: img("Vincent_van_Gogh_-_Self-Portrait_-_Google_Art_Project_(454045).jpg"),
    funFact: "He sold only a handful of paintings during his lifetime.",
  },
  {
    slug: "frida-kahlo",
    firstName: "Frida",
    lastName: "Kahlo",
    fullName: "Frida Kahlo",
    aliases: ["Kahlo"],
    primaryCategory: "art",
    categories: ["art"],
    difficulty: "easy",
    notability: 90,
    birth: { placeLabel: "Coyoacán, Mexico City, Mexico", modernCountry: "Mexico", city: "Mexico City", lat: 19.3551, lng: -99.1626, year: 1907, month: 7, day: 6 },
    death: { placeLabel: "Coyoacán, Mexico City, Mexico", modernCountry: "Mexico", city: "Mexico City", lat: 19.3551, lng: -99.1626, year: 1954, month: 7, day: 13 },
    wikipediaUrl: "https://en.wikipedia.org/wiki/Frida_Kahlo",
    imageUrl: img("Frida_Kahlo,_by_Guillermo_Kahlo.jpg"),
    funFact: "She was born and died in the same house, the Casa Azul.",
  },
  {
    slug: "pablo-picasso",
    firstName: "Pablo",
    lastName: "Picasso",
    fullName: "Pablo Picasso",
    aliases: ["Picasso"],
    primaryCategory: "art",
    categories: ["art"],
    difficulty: "easy",
    notability: 92,
    birth: { placeLabel: "Málaga, Spain", modernCountry: "Spain", city: "Málaga", lat: 36.7213, lng: -4.4214, year: 1881, month: 10, day: 25 },
    death: { placeLabel: "Mougins, France", modernCountry: "France", city: "Mougins", lat: 43.6005, lng: 7.0007, year: 1973, month: 4, day: 8 },
    wikipediaUrl: "https://en.wikipedia.org/wiki/Pablo_Picasso",
    imageUrl: img("Portrait_de_Picasso,_1908.jpg"),
    funFact: "His full baptized name strings together more than 20 words.",
  },
  {
    slug: "ludwig-van-beethoven",
    firstName: "Ludwig",
    lastName: "van Beethoven",
    fullName: "Ludwig van Beethoven",
    aliases: ["Beethoven"],
    primaryCategory: "music",
    categories: ["music"],
    difficulty: "easy",
    notability: 93,
    birth: { placeLabel: "Bonn, Electorate of Cologne", modernCountry: "Germany", city: "Bonn", lat: 50.7374, lng: 7.0982, year: 1770, month: 12, day: 17, circa: true },
    death: { placeLabel: "Vienna, Austria", modernCountry: "Austria", city: "Vienna", lat: 48.2082, lng: 16.3738, year: 1827, month: 3, day: 26 },
    wikipediaUrl: "https://en.wikipedia.org/wiki/Ludwig_van_Beethoven",
    imageUrl: img("Beethoven.jpg"),
    funFact: "He kept composing masterworks after going almost completely deaf.",
  },
  {
    slug: "wolfgang-amadeus-mozart",
    firstName: "Wolfgang",
    lastName: "Mozart",
    fullName: "Wolfgang Amadeus Mozart",
    aliases: ["Mozart"],
    primaryCategory: "music",
    categories: ["music"],
    difficulty: "medium",
    notability: 91,
    birth: { placeLabel: "Salzburg, Archbishopric of Salzburg", modernCountry: "Austria", city: "Salzburg", lat: 47.8009, lng: 13.0438, year: 1756, month: 1, day: 27 },
    death: { placeLabel: "Vienna, Austria", modernCountry: "Austria", city: "Vienna", lat: 48.2082, lng: 16.3738, year: 1791, month: 12, day: 5 },
    wikipediaUrl: "https://en.wikipedia.org/wiki/Wolfgang_Amadeus_Mozart",
    imageUrl: img("Wolfgang-amadeus-mozart_1.jpg"),
    funFact: "He composed his first pieces of music at age five.",
  },
  {
    slug: "david-bowie",
    firstName: "David",
    lastName: "Bowie",
    fullName: "David Bowie",
    aliases: ["Bowie", "David Robert Jones", "Ziggy Stardust"],
    primaryCategory: "music",
    categories: ["music", "film"],
    difficulty: "medium",
    notability: 88,
    birth: { placeLabel: "Brixton, London, England", modernCountry: "United Kingdom", city: "London", lat: 51.4613, lng: -0.1156, year: 1947, month: 1, day: 8 },
    death: { placeLabel: "Manhattan, New York City, USA", modernCountry: "United States", city: "New York City", lat: 40.7128, lng: -74.006, year: 2016, month: 1, day: 10 },
    wikipediaUrl: "https://en.wikipedia.org/wiki/David_Bowie",
    imageUrl: img("David_Bowie_-_TopPop_1974_10.png"),
    funFact: "His differently-colored eyes came from a teenage punch over a girl.",
  },
  {
    slug: "abraham-lincoln",
    firstName: "Abraham",
    lastName: "Lincoln",
    fullName: "Abraham Lincoln",
    aliases: ["Lincoln", "Honest Abe"],
    primaryCategory: "politics",
    categories: ["politics"],
    difficulty: "easy",
    notability: 95,
    birth: { placeLabel: "Hodgenville, Kentucky, USA", modernCountry: "United States", city: "Hodgenville", lat: 37.5739, lng: -85.7394, year: 1809, month: 2, day: 12 },
    death: { placeLabel: "Washington, D.C., USA", modernCountry: "United States", city: "Washington", lat: 38.9047, lng: -77.0353, year: 1865, month: 4, day: 15 },
    wikipediaUrl: "https://en.wikipedia.org/wiki/Abraham_Lincoln",
    imageUrl: img("Abraham_Lincoln_O-77_matte_collodion_print.jpg"),
    funFact: "He is enshrined in the National Wrestling Hall of Fame.",
  },
  {
    slug: "winston-churchill",
    firstName: "Winston",
    lastName: "Churchill",
    fullName: "Winston Churchill",
    aliases: ["Churchill", "Sir Winston Churchill"],
    primaryCategory: "politics",
    categories: ["politics", "military", "literature"],
    difficulty: "medium",
    notability: 92,
    birth: { placeLabel: "Blenheim Palace, Woodstock, England", modernCountry: "United Kingdom", city: "Woodstock", lat: 51.8412, lng: -1.3613, year: 1874, month: 11, day: 30 },
    death: { placeLabel: "Kensington, London, England", modernCountry: "United Kingdom", city: "London", lat: 51.5074, lng: -0.1878, year: 1965, month: 1, day: 24 },
    wikipediaUrl: "https://en.wikipedia.org/wiki/Winston_Churchill",
    imageUrl: img("Sir_Winston_Churchill_-_19086236948.jpg"),
    funFact: "He won the 1953 Nobel Prize in Literature.",
  },
  {
    slug: "cleopatra",
    firstName: "Cleopatra",
    lastName: "VII",
    fullName: "Cleopatra VII",
    aliases: ["Cleopatra"],
    primaryCategory: "politics",
    categories: ["politics"],
    difficulty: "hard",
    notability: 89,
    birth: { placeLabel: "Alexandria, Ptolemaic Egypt", modernCountry: "Egypt", city: "Alexandria", lat: 31.2001, lng: 29.9187, year: -69, circa: true },
    death: { placeLabel: "Alexandria, Egypt", modernCountry: "Egypt", city: "Alexandria", lat: 31.2001, lng: 29.9187, year: -30, month: 8, circa: true },
    wikipediaUrl: "https://en.wikipedia.org/wiki/Cleopatra",
    imageUrl: img("Kleopatra-VII.-Altes-Museum-Berlin1.jpg"),
    funFact: "She reportedly spoke as many as nine languages.",
  },
  {
    slug: "william-shakespeare",
    firstName: "William",
    lastName: "Shakespeare",
    fullName: "William Shakespeare",
    aliases: ["Shakespeare", "The Bard"],
    primaryCategory: "literature",
    categories: ["literature"],
    difficulty: "medium",
    notability: 94,
    birth: { placeLabel: "Stratford-upon-Avon, England", modernCountry: "United Kingdom", city: "Stratford-upon-Avon", lat: 52.1917, lng: -1.7073, year: 1564, month: 4, circa: true },
    death: { placeLabel: "Stratford-upon-Avon, England", modernCountry: "United Kingdom", city: "Stratford-upon-Avon", lat: 52.1917, lng: -1.7073, year: 1616, month: 4, day: 23 },
    wikipediaUrl: "https://en.wikipedia.org/wiki/William_Shakespeare",
    imageUrl: img("Shakespeare.jpg"),
    funFact: "He coined hundreds of words still in everyday English.",
  },
  {
    slug: "ernest-hemingway",
    firstName: "Ernest",
    lastName: "Hemingway",
    fullName: "Ernest Hemingway",
    aliases: ["Hemingway"],
    primaryCategory: "literature",
    categories: ["literature"],
    difficulty: "hard",
    notability: 85,
    birth: { placeLabel: "Oak Park, Illinois, USA", modernCountry: "United States", city: "Oak Park", lat: 41.885, lng: -87.7845, year: 1899, month: 7, day: 21 },
    death: { placeLabel: "Ketchum, Idaho, USA", modernCountry: "United States", city: "Ketchum", lat: 43.6805, lng: -114.3636, year: 1961, month: 7, day: 2 },
    wikipediaUrl: "https://en.wikipedia.org/wiki/Ernest_Hemingway",
    imageUrl: img("ErnestHemingway.jpg"),
    funFact: "He survived two plane crashes on back-to-back days in Africa.",
  },
  {
    slug: "napoleon-bonaparte",
    firstName: "Napoleon",
    lastName: "Bonaparte",
    fullName: "Napoleon Bonaparte",
    aliases: ["Napoleon", "Napoleon I"],
    primaryCategory: "military",
    categories: ["military", "politics"],
    difficulty: "medium",
    notability: 93,
    birth: { placeLabel: "Ajaccio, Corsica, France", modernCountry: "France", city: "Ajaccio", lat: 41.9192, lng: 8.7386, year: 1769, month: 8, day: 15 },
    death: { placeLabel: "Longwood, Saint Helena", modernCountry: "Saint Helena", city: "Longwood", lat: -15.9417, lng: -5.7089, year: 1821, month: 5, day: 5 },
    wikipediaUrl: "https://en.wikipedia.org/wiki/Napoleon",
    imageUrl: img("Jacques-Louis_David_-_The_Emperor_Napoleon_in_His_Study_at_the_Tuileries_-_Google_Art_Project.jpg"),
    funFact: "He was not unusually short — the 'tiny Napoleon' image was British propaganda.",
  },
  {
    slug: "ferdinand-magellan",
    firstName: "Ferdinand",
    lastName: "Magellan",
    fullName: "Ferdinand Magellan",
    aliases: ["Magellan", "Fernão de Magalhães"],
    primaryCategory: "exploration",
    categories: ["exploration"],
    difficulty: "hard",
    notability: 80,
    birth: { placeLabel: "Sabrosa, Kingdom of Portugal", modernCountry: "Portugal", city: "Sabrosa", lat: 41.2625, lng: -7.5747, year: 1480, circa: true },
    death: { placeLabel: "Mactan, Philippines", modernCountry: "Philippines", city: "Mactan", lat: 10.3103, lng: 123.9494, year: 1521, month: 4, day: 27 },
    wikipediaUrl: "https://en.wikipedia.org/wiki/Ferdinand_Magellan",
    imageUrl: img("Ferdinand_Magellan.jpg"),
    funFact: "He died mid-voyage; his crew completed the first circumnavigation without him.",
  },
  {
    slug: "charlie-chaplin",
    firstName: "Charlie",
    lastName: "Chaplin",
    fullName: "Charlie Chaplin",
    aliases: ["Chaplin", "Charles Chaplin", "The Tramp"],
    primaryCategory: "film",
    categories: ["film"],
    difficulty: "medium",
    notability: 87,
    birth: { placeLabel: "Walworth, London, England", modernCountry: "United Kingdom", city: "London", lat: 51.4877, lng: -0.0998, year: 1889, month: 4, day: 16 },
    death: { placeLabel: "Corsier-sur-Vevey, Switzerland", modernCountry: "Switzerland", city: "Corsier-sur-Vevey", lat: 46.4626, lng: 6.8331, year: 1977, month: 12, day: 25 },
    wikipediaUrl: "https://en.wikipedia.org/wiki/Charlie_Chaplin",
    imageUrl: img("Charlie_Chaplin.jpg"),
    funFact: "He reportedly once placed in a Chaplin look-alike contest — and lost.",
  },
  {
    slug: "muhammad-ali",
    firstName: "Muhammad",
    lastName: "Ali",
    fullName: "Muhammad Ali",
    aliases: ["Ali", "Cassius Clay", "The Greatest"],
    primaryCategory: "sports",
    categories: ["sports"],
    difficulty: "medium",
    notability: 88,
    birth: { placeLabel: "Louisville, Kentucky, USA", modernCountry: "United States", city: "Louisville", lat: 38.2527, lng: -85.7585, year: 1942, month: 1, day: 17 },
    death: { placeLabel: "Scottsdale, Arizona, USA", modernCountry: "United States", city: "Scottsdale", lat: 33.4942, lng: -111.9261, year: 2016, month: 6, day: 3 },
    wikipediaUrl: "https://en.wikipedia.org/wiki/Muhammad_Ali",
    imageUrl: img("Muhammad_Ali_NYWTS.jpg"),
    funFact: "He won an Olympic gold medal in Rome before turning professional.",
  },
];
